// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaBiblioteca.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinhaBiblioteca.Infrastructure.Migrations
{
    [DbContext(typeof(MinhaBibliotecaDbContext))]
    [Migration("20241024175600_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9946192a-3920-4fa8-abbe-80568241fb0e"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1698),
                            Name = "Ação",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1699)
                        },
                        new
                        {
                            Id = new Guid("3219f776-4516-472e-b872-cc2561a87089"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1714),
                            Name = "Aventura",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1716)
                        },
                        new
                        {
                            Id = new Guid("4fc2e6ff-7d37-41eb-8c04-c7cf18769a53"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1728),
                            Name = "Romance",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1729)
                        },
                        new
                        {
                            Id = new Guid("aed48971-3ba4-4b58-a148-2c5c39983b50"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1741),
                            Name = "Ficção Científica",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1742)
                        },
                        new
                        {
                            Id = new Guid("6134c6b0-da2b-48d6-9661-951fce12c00b"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1754),
                            Name = "Fantasia",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1755)
                        },
                        new
                        {
                            Id = new Guid("ad3902fd-9a3d-4d97-967a-bfc711c71029"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1766),
                            Name = "Biografia",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1767)
                        },
                        new
                        {
                            Id = new Guid("d52b9604-0115-4a46-9ebf-50c783e5a240"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1779),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1780)
                        },
                        new
                        {
                            Id = new Guid("f22c7c45-239f-49e8-a48a-90f6a7afeeb4"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1792),
                            Name = "Mistério",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1793)
                        },
                        new
                        {
                            Id = new Guid("4f9d35d7-e889-4fe3-8136-39efcfc5c3e8"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1805),
                            Name = "Terror",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1805)
                        },
                        new
                        {
                            Id = new Guid("d777686d-ad6e-47ba-a0d5-006d06f794c5"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1817),
                            Name = "Autoajuda",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1818)
                        },
                        new
                        {
                            Id = new Guid("37bd3107-f71f-4163-9d2d-1b6584ccd33c"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1829),
                            Name = "Poesia",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1830)
                        },
                        new
                        {
                            Id = new Guid("dca4797d-da2c-4c2e-a3ae-1d1987917f4d"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1842),
                            Name = "Drama",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1843)
                        },
                        new
                        {
                            Id = new Guid("717ce636-8d8c-435a-bc62-13502d34c56a"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1855),
                            Name = "Humor",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1856)
                        },
                        new
                        {
                            Id = new Guid("49b8f6bd-0ec4-47ce-9dc8-61aff779a05c"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1867),
                            Name = "Tecnologia",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1868)
                        },
                        new
                        {
                            Id = new Guid("0cc9e10d-5330-43a7-a256-3f00e7a111b9"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1880),
                            Name = "Negócios",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1881)
                        },
                        new
                        {
                            Id = new Guid("42d3e87a-d800-4cad-8e1b-df3d6bcf28ee"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1892),
                            Name = "Saúde",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1893)
                        },
                        new
                        {
                            Id = new Guid("6e7523d1-e7c0-49b8-adc0-a7fea794dcd3"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1904),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1905)
                        },
                        new
                        {
                            Id = new Guid("ea53d7fa-4e44-48fd-b6d0-4244ff403fc9"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1917),
                            Name = "Religião",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1918)
                        },
                        new
                        {
                            Id = new Guid("59c38890-e8a3-4f9f-b05e-39f45ce51b20"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1930),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1931)
                        },
                        new
                        {
                            Id = new Guid("c0f59472-43d8-43f5-bec3-72b41549673f"),
                            CreatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1942),
                            Name = "Arte",
                            UpdatedAt = new DateTime(2024, 10, 24, 17, 56, 0, 187, DateTimeKind.Utc).AddTicks(1943)
                        });
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Loan", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.BookCopy", "BookCopy")
                        .WithOne("Loan")
                        .HasForeignKey("MinhaBiblioteca.Core.Entities.Loan", "BookCopyId");

                    b.HasOne("MinhaBiblioteca.Core.Entities.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.User", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
