// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaBiblioteca.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinhaBiblioteca.Infrastructure.Migrations
{
    [DbContext(typeof(MinhaBibliotecaDbContext))]
    [Migration("20241028113217_AddManyToManyInLoansCopiesOfTheBook")]
    partial class AddManyToManyInLoansCopiesOfTheBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e9af7a0-5543-42d9-b222-082354502e17"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3965),
                            Name = "Ação",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3966)
                        },
                        new
                        {
                            Id = new Guid("bb98d688-80e1-49ce-a9b3-92fca36a0b55"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3971),
                            Name = "Aventura",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3971)
                        },
                        new
                        {
                            Id = new Guid("3de6cf8e-b487-4477-a2e4-04e4f093bae3"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3976),
                            Name = "Romance",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3976)
                        },
                        new
                        {
                            Id = new Guid("2391e2bc-e316-4d2d-8177-c9c77490ec5a"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3980),
                            Name = "Ficção Científica",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3980)
                        },
                        new
                        {
                            Id = new Guid("cc5ce429-1295-4d68-be86-0d8a178d3461"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3985),
                            Name = "Fantasia",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3985)
                        },
                        new
                        {
                            Id = new Guid("debc9601-1d73-4561-8774-1f5d2365e8ef"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3989),
                            Name = "Biografia",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3990)
                        },
                        new
                        {
                            Id = new Guid("951a1f02-ebc6-41da-85c2-4364cb1c3b26"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3994),
                            Name = "História",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3994)
                        },
                        new
                        {
                            Id = new Guid("d96a5eeb-4713-4580-9076-79bf07249c79"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3999),
                            Name = "Mistério",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(3999)
                        },
                        new
                        {
                            Id = new Guid("03658c3d-d92e-48c3-8ceb-270473123299"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4003),
                            Name = "Terror",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4003)
                        },
                        new
                        {
                            Id = new Guid("7b678ab6-26f6-4857-87d9-5ab276a60b18"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4007),
                            Name = "Autoajuda",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4008)
                        },
                        new
                        {
                            Id = new Guid("dbf6e799-8b73-4491-bd2d-c4bc237baeb8"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4012),
                            Name = "Poesia",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4012)
                        },
                        new
                        {
                            Id = new Guid("d1c99335-1e96-40c6-8ced-ee6928cb634a"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4016),
                            Name = "Drama",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4017)
                        },
                        new
                        {
                            Id = new Guid("0eb5ff7a-bf20-467f-88eb-ad4a9e416cf4"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4021),
                            Name = "Humor",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4021)
                        },
                        new
                        {
                            Id = new Guid("25d750fb-9a0a-4135-8520-4116f70238f9"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4025),
                            Name = "Tecnologia",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4025)
                        },
                        new
                        {
                            Id = new Guid("92ab711d-b075-4b6f-a8f1-47bbec684f94"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4030),
                            Name = "Negócios",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4030)
                        },
                        new
                        {
                            Id = new Guid("7f29d28c-ce0a-4976-b130-a7cd51ea18c0"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4034),
                            Name = "Saúde",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4034)
                        },
                        new
                        {
                            Id = new Guid("dd1ad99b-b10b-4752-be50-e1625c3ac987"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4038),
                            Name = "Educação",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4039)
                        },
                        new
                        {
                            Id = new Guid("1a6c942f-5b97-4e98-85a4-70049450d2a3"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4043),
                            Name = "Religião",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4043)
                        },
                        new
                        {
                            Id = new Guid("3bc3581c-77d6-415a-bf58-680c084e6730"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4047),
                            Name = "Filosofia",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4047)
                        },
                        new
                        {
                            Id = new Guid("a6b7efc7-724e-438f-8ff2-e2b4821f6b30"),
                            CreatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4051),
                            Name = "Arte",
                            UpdatedAt = new DateTime(2024, 10, 28, 11, 32, 17, 382, DateTimeKind.Utc).AddTicks(4052)
                        });
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Loan", b =>
                {
                    b.HasOne("MinhaBiblioteca.Core.Entities.BookCopy", "BookCopy")
                        .WithMany("Loan")
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaBiblioteca.Core.Entities.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.BookCopy", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MinhaBiblioteca.Core.Entities.User", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
